# site settings
title: PSConf EU 2020
subtitle: "Hannover, Germany"
email: tobias@powertheshell.com
description: June 2-5, 2020&nbsp;<br />Hannover, Germany
baseurl: # the subpath of your site, e.g. /blog
url: //psconf.eu
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/psconfeu

# build settings
markdown: kramdown

sass:
  style: compressed
